@startuml General
actor Jugador order 10
boundary Prueba order 20

participant Usuario order 30
participant UsuarioConEjercitoDefault order 40 
participant UsuarioConEjercitoExplorador order 50
participant UsuarioConEjercitoKamikaze order 60

participant Comandante order 70
participant Soldado order 80
participant Enemigo order 90

Prueba -> Jugador : Muestra las opciones de ejercito

Jugador -> Prueba : Selecciona una opcion de ejercito

create Usuario
Prueba -> Usuario

alt opcion == 1
    Usuario -> UsuarioConEjercitoExplorador: crea un ejercito
    Usuario <- UsuarioConEjercitoExplorador: Devuelve un ejercito de tipo explorador
else opcion == 2
    Usuario -> UsuarioConEjercitoDefault: crea un ejercito
    Usuario <- UsuarioConEjercitoDefault: Devuelve un ejercito de tipo default
else opcion == 3
    Usuario -> UsuarioConEjercitoKamikaze: crea un ejercito
    Usuario <- UsuarioConEjercitoKamikaze: Devuelve un ejercito de tipo default
else
    Jugador <- Prueba: "<font color=red><b>Lanza un mensaje de error"
end
Usuario <- Usuario: Almacena en una variable el ejercito creado

Jugador <- Prueba : Muestra el ataque del enemigo al jugador
Jugador <- Prueba : Muestra el vida del enemigo al jugador
Jugador <- Prueba : Muestra la distancia inicial del enemigo al jugador

loop El enemigo este vivo y el usuario tenga al menos un soldado vivo en su ejercito
    Jugador <- Prueba : Muestra las opciones para jugar

    Jugador -> Prueba : Escoge una opcion
    alt  opcion == 1
        Prueba -> Usuario: Ordenar ataque

        Usuario -> Comandante : Ordena un ataque al enemigo

        Comandante -> Soldado : Ordena un ataque al enemigo

        Soldado -> Enemigo: Disminuye tu vida

        Enemigo -> Enemigo: Disminuye su propia vida

    else opcion == 2
        Prueba -> Usuario: Ordenar movimiento

        Usuario -> Comandante: Ordena movimiento

        Comandante -> Soldado: Ordena movimiento

        Soldado -> Soldado: Disminuye la distancia al enemigo
    else opcion == 3
        Prueba -> Usuario: Ordenar reportarse

        Usuario -> Comandante: Ordena reportarse

        Comandante -> Soldado: Ordena reportarse

        Soldado -> Soldado: Imprime informacion acerca de estado actual
    else
        Jugador <- Prueba: "<font color=red><b>Lanza un mensaje de error"
    end

    Prueba -> Prueba: Genera un numero aleatorio

    alt aleatorio > "0.5"
        Prueba -> Enemigo: Ordena ataque del enemigo

        Enemigo -> Usuario : Disminuye tu vida

        Usuario -> Comandante : Disminuye tu vida

        Comandante -> Soldado : Disminuye tu vida

        Soldado -> Soldado:  Disminuye su propia vida
    end
end

alt El enemigo esta muerto
    Jugador <- Prueba : Muesta un mensaje de victoria
else
    Jugador <- Prueba : Muesta un mensaje de derrota
end






@enduml